<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encryption.proto

namespace Encryption;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request untuk enkripsi
 *
 * Generated from protobuf message <code>encryption.EncryptRequest</code>
 */
class EncryptRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string plain_text = 1;</code>
     */
    protected $plain_text = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $plain_text
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Encryption::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string plain_text = 1;</code>
     * @return string
     */
    public function getPlainText()
    {
        return $this->plain_text;
    }

    /**
     * Generated from protobuf field <code>string plain_text = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlainText($var)
    {
        GPBUtil::checkString($var, True);
        $this->plain_text = $var;

        return $this;
    }

}

