<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encryption.proto

namespace Encryption;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Respon enkripsi (mengirim ciphertext dan IV untuk dekripsi nanti)
 *
 * Generated from protobuf message <code>encryption.EncryptResponse</code>
 */
class EncryptResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes cipher_text = 1;</code>
     */
    protected $cipher_text = '';
    /**
     * Generated from protobuf field <code>bytes iv = 2;</code>
     */
    protected $iv = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cipher_text
     *     @type string $iv
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Encryption::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes cipher_text = 1;</code>
     * @return string
     */
    public function getCipherText()
    {
        return $this->cipher_text;
    }

    /**
     * Generated from protobuf field <code>bytes cipher_text = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCipherText($var)
    {
        GPBUtil::checkString($var, False);
        $this->cipher_text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes iv = 2;</code>
     * @return string
     */
    public function getIv()
    {
        return $this->iv;
    }

    /**
     * Generated from protobuf field <code>bytes iv = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setIv($var)
    {
        GPBUtil::checkString($var, False);
        $this->iv = $var;

        return $this;
    }

}

