<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encryption.proto

namespace GPBMetadata;

class Encryption
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ø
encryption.proto
encryption"$
EncryptRequest

plain_text (	"2
EncryptResponse
cipher_text (

iv ("1
DecryptRequest
cipher_text (

iv ("%
DecryptResponse

plain_text (	2›
EncryptionServiceB
Encrypt.encryption.EncryptRequest.encryption.EncryptResponseB
Decrypt.encryption.DecryptRequest.encryption.DecryptResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

